### ISSUE TITLE
完成が待ち遠しい

### ISSUE THREAD

**Issue by purinx** [serviver-agent/cafe-backend#6]
```
play.sbt.PlayExceptions$CompilationException: Compilation error[not found: type UserRefinerImpl]
	at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:37)
	at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:37)
	at scala.Option.map(Option.scala:163)
	at play.sbt.run.PlayReload$.$anonfun$taskFailureHandler$1(PlayReload.scala:41)
	at scala.Option.map(Option.scala:163)
	at play.sbt.run.PlayReload$.taskFailureHandler(PlayReload.scala:36)
	at play.sbt.run.PlayReload$.compileFailure(PlayReload.scala:29)
	at play.sbt.run.PlayReload$.$anonfun$compile$3(PlayReload.scala:64)
	at scala.util.Either$LeftProjection.map(Either.scala:573)
	at play.sbt.run.PlayReload$.compile(PlayReload.scala:64)
```

**Comment by KazuyaMiyashita** [comment]
えっこれマ？手元でこれ確認できませんが

**Comment by purinx** [comment]
5分経ちました

**Comment by KazuyaMiyashita** [comment]
対応しました。
* 差分コンパイルに失敗していた
* クラス名同じでクラスをインターフェースに変更したり、アクセス権限を変えた時に差分コンパイルが走らない
* そういうとき　`clean` `compile` するべき
でした（ごめん）

https://github.com/serviver-agent/cafe-backend/commit/c660ea0bae36d7d764626d9c066108033d169224
